framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    enabled_locales: ['en']

    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
        utf8: true

    validation:
        email_validation_mode: html5

when@tst:
    framework:
        test: true

when@prd:
    framework:
        router:
            strict_requirements: null
