version: '3.9'

x-env-app-shared: &env-app-shared
  APP_ENV: ${APP_ENV}
  APP_DEBUG: ${APP_DEBUG}
  APP_RELEASE: ${APP_RELEASE}
  APP_HOME_DIR: ${APP_HOME_DIR}
  APP_GATEWAY_CLI: ${APP_GATEWAY_CLI}
  APP_GATEWAY_WEB: ${APP_GATEWAY_WEB}

services:

  web:
    profiles: ['dev', 'stg']
    image: ghcr.io/d-paniutycz/skeleton-docker/be/app/web:1.1
    environment:
      <<: *env-app-shared
      APP_PHP_HOST: ${APP_PHP_HOST}
      APP_PHP_PORT: ${APP_PHP_PORT}
    depends_on:
      php:
        condition: service_started
    ports:
      - '${APP_PHP_PORT}:${APP_PHP_PORT}'

  php-ini:
    image: ${APP_PHP_IMG_URI}:${APP_PHP_IMG_TAG}
    working_dir: ${APP_HOME_DIR}
    environment:
      <<: *env-app-shared
      APP_SECRET: ${APP_SECRET}
      DMS_PG1_PRI_PASSWORD: ${DMS_PG1_PRI_PASSWORD}
      DMS_PG1_REP_PASSWORD: ${DMS_PG1_REP_PASSWORD}

  php:
    profiles: ['dev', 'tst', 'stg']
    extends:
      service: php-ini
    depends_on:
      php-ini:
        condition: service_completed_successfully

  # local mock
  dms-pg1:
    profiles: ['dev', 'tst']
    image: bitnami/postgresql:15.2.0-debian-11-r14
    environment:
      POSTGRES_DATABASE: ${DMS_PG1_DATABASE}
      POSTGRES_USERNAME: ${DMS_PG1_PRI_USERNAME}
      POSTGRES_PASSWORD: ${DMS_PG1_PRI_PASSWORD}
