# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_name: '%env(COMPOSE_PROJECT_NAME)%'
    app_env: '%env(APP_ENV)%'
    app_release: '%env(APP_RELEASE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '%kernel.project_dir%/src/App'
    Sys\:
        resource: '%kernel.project_dir%/src/Sys'
        exclude: '%kernel.project_dir%/src/Sys/Framework/Infrastructure/Kernel.php'

    # Resolvers
    Sys\Infrastructure\Resolver\UniqueStringValueResolver:
        tags: [ { name: controller.argument_value_resolver, priority: 150 } ]

    _instanceof:
        # Messenger handlers
        Sys\Application\Messenger\Handler\CommandHandler:
            tags: [ { name: messenger.message_handler, bus: command } ]
        Sys\Application\Messenger\Handler\QueryHandler:
            tags: [ { name: messenger.message_handler, bus: query } ]
        Sys\Application\Messenger\Handler\EventHandler:
            tags: [ { name: messenger.message_handler, bus: event } ]
        # Controllers
        Sys\Infrastructure\Controller\WebController:
            tags: [ { name: controller.service_arguments } ]