# @TODO: move to separate yaml after reworking loaders in kernel class
parameters:
    app_name: '%env(COMPOSE_PROJECT_NAME)%'
    app_env: '%env(APP_ENV)%'
    app_release: '%env(APP_RELEASE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true # @TODO: set to false after writing tests to prevent double configuration

    # @TODO: add some "exclude:" with "glob" after writing tests as it slows the dev env
    App\:
        resource: '%kernel.project_dir%/src/App'
    Sys\:
        resource: '%kernel.project_dir%/src/Sys'

    # Resolvers
    Sys\Infrastructure\Resolver\UniqueStringIdValueResolver:
        tags: [ { name: controller.argument_value_resolver, priority: 128 } ]

    _instanceof:
        # Messenger handlers
        Sys\Application\Messenger\Handler\CommandHandler:
            tags: [ { name: messenger.message_handler, bus: command } ]
        Sys\Application\Messenger\Handler\QueryHandler:
            tags: [ { name: messenger.message_handler, bus: query } ]
        Sys\Application\Messenger\Handler\EventHandler:
            tags: [ { name: messenger.message_handler, bus: event } ]
        # Controllers
        Sys\Infrastructure\Controller\WebController:
            tags: [ { name: controller.service_arguments } ]
