# @TODO: move to separate yaml after reworking loaders in kernel class
parameters:
    app_name: '%env(COMPOSE_PROJECT_NAME)%'
    app_env: '%env(APP_ENV)%'
    app_release: '%env(APP_RELEASE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '%kernel.project_dir%/src/App'
        exclude:
            - '%kernel.project_dir%/src/App/**/Domain/{Value,Event,Entity}'
            - '%kernel.project_dir%/src/App/**/Application/{Model,Exception}'
            - '%kernel.project_dir%/src/App/**/Port/Api/Message'

    Sys\:
        resource: '%kernel.project_dir%/src/Sys'
        exclude:
            - '%kernel.project_dir%/src/Sys/Domain'
            - '%kernel.project_dir%/src/Sys/Application/{Model,Exception}'

    # Resolvers
    Sys\Infrastructure\Port\Web\Resolver\Value\UlidValueResolver:
        tags: [ { name: controller.argument_value_resolver, priority: 256 } ]
    Sys\Infrastructure\Port\Web\Resolver\Request\RequestResolver:
        tags: [ { name: controller.argument_value_resolver, priority: 128 } ]

    _instanceof:
        # Messenger handlers
        Sys\Application\Messenger\Handler\CommandHandler:
            tags: [ { name: messenger.message_handler, bus: command.bus } ]
        Sys\Application\Messenger\Handler\QueryHandler:
            tags: [ { name: messenger.message_handler, bus: query.bus } ]
        Sys\Application\Messenger\Handler\EventHandler:
            tags: [ { name: messenger.message_handler, bus: event.bus } ]
        # Controllers
        Sys\Infrastructure\Port\Web\WebController:
            tags: [ { name: controller.service_arguments } ]
