version: '3.9'

services:

  web:
    environment:
      NGINX_WORKER_PROCESSES: 1
    restart: 'no'
    deploy:
      mode: global

  php-ini:
    command: sh -c "bin/app init composer symfony doctrine"
    volumes:
      - .:${APP_HOME_DIR}
    depends_on:
      pg1:
        condition: service_healthy
    restart: 'no'
    deploy:
      mode: global

  php:
    volumes:
      - .:${APP_HOME_DIR}
    restart: 'no'
    deploy:
      mode: replicated
      replicas: 1

  # local mock (dms)
  pg1:
    restart: 'no'
    deploy:
      mode: global
